[versions]
agp = "9.4.1"
kotlin = "2.4.20"
composeBom = "2026.09.00"
activityCompose = "1.13.0"
coreKtx = "1.19.1"
lifecycle = "2.11.0"
profileinstaller = "1.4.1"
ink = "1.1.0-alpha09"
motionprediction = "1.0.0"
mlkitInchiostro = "19.0.0"
junit = "4.13.2"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileinstaller" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

ink-authoring = { module = "androidx.ink:ink-authoring", version.ref = "ink" }
ink-brush = { module = "androidx.ink:ink-brush", version.ref = "ink" }
ink-strokes = { module = "androidx.ink:ink-strokes", version.ref = "ink" }
ink-rendering = { module = "androidx.ink:ink-rendering", version.ref = "ink" }
ink-geometry = { module = "androidx.ink:ink-geometry", version.ref = "ink" }
androidx-motionprediction = { module = "androidx.input:input-motionprediction", version.ref = "motionprediction" }
mlkit-digital-ink = { module = "com.google.mlkit:digital-ink-recognition", version.ref = "mlkitInchiostro" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
